import type { Metadata } from "next";
import type { ReactNode } from "react";
import "katex/dist/katex.min.css";
import "./globals.css";
import { OfflineBanner } from "@/components/offline-banner";
import { SwRegister } from "@/components/sw-register";

export const metadata: Metadata = {
  title: "DocForge",
  description:
    "Plain text in, beautifully typeset PDF and Word documents out — local-first, no account, yours forever.",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    // The day desk is the default the app boots into; the ThemeScript below
    // restores a saved night-shift preference before first paint.
    <html lang="en" data-light="">
      <head>
        <script
          // Inline so the desk never flashes the wrong shift on load.
          // biome-ignore lint/security/noDangerouslySetInnerHtml: static string, no interpolation
          dangerouslySetInnerHTML={{
            __html: `try{if(localStorage.getItem("docforge.ui.theme")==="dark")document.documentElement.removeAttribute("data-light")}catch(e){}`,
          }}
        />
        {/* The embedded faces, served as static cuts (generated by sync-assets). */}
        <link
          rel="preload"
          href="/fonts/DocForgeInter-Regular.ttf"
          as="font"
          type="font/ttf"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/DocForgeInter-Bold.ttf"
          as="font"
          type="font/ttf"
          crossOrigin="anonymous"
        />
        <link rel="stylesheet" href="/fonts.css" />
      </head>
      <body>
        <SwRegister />
        <OfflineBanner />
        {children}
      </body>
    </html>
  );
}
