/* Stage the product surfaces the studio serves verbatim:
     public/doc.css    — THE document stylesheet (src/doc.css is sacred; copied, never edited)
     public/fonts/*    — the embedded OFL cuts
     public/fonts.css  — @font-face over static URLs, mirroring engine.fontFaceCss()
   Runs before dev and build (predev/prebuild). */
import { copyFileSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const APP = resolve(fileURLToPath(new URL(".", import.meta.url)), "..");
const REPO = resolve(APP, "..", "..");
const PUB = join(APP, "public");

mkdirSync(join(PUB, "fonts"), { recursive: true });
copyFileSync(join(REPO, "src", "doc.css"), join(PUB, "doc.css"));

/* Paged.js rides in as the prebuilt UMD (the same build the classic edition
   inlines): its ESM source drags es5-ext "#" deep paths Turbopack mis-resolves,
   and the package exports map hides dist/. Vendored copy, gitignored. */
mkdirSync(join(APP, "lib", "vendor"), { recursive: true });
copyFileSync(
  join(REPO, "node_modules", "pagedjs", "dist", "paged.js"),
  join(APP, "lib", "vendor", "paged.cjs"),
);

const CUT_STYLE = {
  Regular: { weight: 400, style: "normal" },
  Bold: { weight: 700, style: "normal" },
  Italic: { weight: 400, style: "italic" },
  BoldItalic: { weight: 700, style: "italic" },
};
/* stem → shipped family name, mirroring EMBEDDED in packages/engine/src/themes.ts
   (that table is the authority; keep the two in step). */
const FACE = {
  DocForgeSans: "DocForge Sans",
  DocForgeSerif: "DocForge Serif",
  DocForgeMono: "DocForge Mono",
  DocForgeInter: "DocForge Inter",
  DocForgeMont: "DocForge Montserrat",
  DocForgeGaramond: "DocForge Garamond",
  DocForgeCrimson: "DocForge Crimson",
};

let css = "/* generated by scripts/sync-assets.mjs — do not edit */\n";
for (const f of readdirSync(join(REPO, "fonts")).filter((f) => f.endsWith(".ttf")).sort()) {
  copyFileSync(join(REPO, "fonts", f), join(PUB, "fonts", f));
  const m = /^(.+)-(Regular|Bold|Italic|BoldItalic)\.ttf$/.exec(f);
  if (!m) continue;
  const family = FACE[m[1]];
  const s = CUT_STYLE[m[2]];
  if (!family || !s) continue;
  css += `@font-face{font-family:"${family}";font-style:${s.style};font-weight:${s.weight};font-display:block;src:url("/fonts/${f}") format("truetype")}\n`;
}
writeFileSync(join(PUB, "fonts.css"), css);
console.log("[sync-assets] doc.css, fonts/, fonts.css staged");
