/* Visual QA: render the torture document, export both formats, rasterise both,
   and emit a side-by-side contact sheet.

   Usage:
     node qa/visual.mjs                       # default matrix, label "current"
     node qa/visual.mjs --label before        # tag this capture
     node qa/visual.mjs --only academic-a4    # a single case
     node qa/visual.mjs --no-word             # skip the Word round-trip
*/
import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync } from "node:fs";
import { resolve, join, basename } from "node:path";
import { execFileSync } from "node:child_process";
import { launch } from "./_browser.mjs";
import { rasterise, pdfText } from "./_raster.mjs";
import * as drive from "./_drive.mjs";

const argv = process.argv.slice(2);
const arg = (n, d) => { const i = argv.indexOf("--" + n); return i === -1 ? d : argv[i + 1]; };
const flag = n => argv.includes("--" + n);

const LABEL = arg("label", "current");
const ONLY = arg("only", null);
const WITH_WORD = !flag("no-word") && process.platform === "win32";
const OUT = resolve("qa/out", LABEL);

const SOURCE = readFileSync(resolve("qa/torture.md"), "utf8");

const BASE = {
  title: "Typographic Torture Test",
  subtitle: "Every construct that has historically broken the layout, on one document",
  author: "DocForge QA",
  kicker: "Quality assurance",
  metaExtra: "Generated by qa/visual.mjs",
  date: "2026-07-31",
};

const CASES = [
  { id: "modern-a4", settings: { ...BASE, theme: "modern", accent: "#2563eb", page: "A4", margins: "normal", cover: true, header: true, pageNums: true, numbered: false, justify: false, h1break: false } },
  { id: "academic-a4", settings: { ...BASE, theme: "academic", accent: "#7f1d1d", page: "A4", margins: "normal", cover: true, header: true, pageNums: true, numbered: true, justify: true, h1break: true } },
  { id: "executive-letter", settings: { ...BASE, theme: "executive", accent: "#1f3a5f", page: "Letter", margins: "wide", cover: true, header: true, pageNums: true, numbered: false, justify: true, h1break: false } },
  { id: "minimal-a4-narrow", settings: { ...BASE, theme: "minimal", accent: "#111827", page: "A4", margins: "narrow", cover: false, header: true, pageNums: true, numbered: true, justify: false, h1break: false } },
];

function docxToPdf(docxPath, pdfPath) {
  const out = execFileSync(
    "powershell",
    ["-NoProfile", "-ExecutionPolicy", "Bypass", "-File", resolve("qa/_docx2pdf.ps1"), "-In", docxPath, "-Out", pdfPath],
    { encoding: "utf8", timeout: 240000 }
  );
  return (out.match(/PAGES=(\d+)/) || [])[1];
}

const report = [];

const browser = await launch();
try {
  for (const c of CASES) {
    if (ONLY && c.id !== ONLY) continue;
    const dir = join(OUT, c.id);
    if (existsSync(dir)) rmSync(dir, { recursive: true, force: true });
    mkdirSync(dir, { recursive: true });

    process.stdout.write(`\n── ${c.id} ────────────────────────────────\n`);
    const page = await drive.open(browser);
    await drive.applyDoc(page, { source: SOURCE, settings: c.settings });

    const pages = await drive.pageCount(page);
    console.log(`  preview pages: ${pages}`);

    const pdfPath = join(dir, "pdf.pdf");
    await drive.printPdf(page, pdfPath);
    const pdfPages = await rasterise(pdfPath, join(dir, "pdf"), { browser, scale: 2 });
    console.log(`  pdf pages: ${pdfPages.total}`);

    const texts = await pdfText(pdfPath, { browser });
    const vector = texts.join("").replace(/\s+/g, "").length;
    console.log(`  pdf selectable characters: ${vector}`);

    let docxPages = null, docxRaster = null;
    const docxPath = join(dir, "word.docx");
    await drive.exportDocx(page, docxPath);
    if (WITH_WORD) {
      try {
        const wordPdf = join(dir, "word.pdf");
        docxPages = docxToPdf(docxPath, wordPdf);
        docxRaster = await rasterise(wordPdf, join(dir, "docx"), { browser, scale: 2 });
        console.log(`  word pages: ${docxPages}`);
      } catch (e) {
        console.log(`  word conversion failed: ${String(e).split("\n")[0].slice(0, 160)}`);
      }
    }

    const errors = page.__errors.filter(e => !/favicon/i.test(e));
    if (errors.length) console.log(`  CONSOLE ERRORS: ${errors.slice(0, 5).join(" | ")}`);
    else console.log("  console errors: none");

    report.push({
      id: c.id,
      previewPages: pages,
      pdfPages: pdfPages.total,
      docxPages: docxPages ? +docxPages : null,
      selectableChars: vector,
      errors,
      pdfImgs: pdfPages.files.map(f => `${c.id}/pdf/${basename(f)}`),
      docxImgs: docxRaster ? docxRaster.files.map(f => `${c.id}/docx/${basename(f)}`) : [],
    });

    await page.context().close();
  }
} finally {
  await browser.close();
}

/* ---- contact sheet ---- */
const html = `<!doctype html><meta charset=utf-8><title>DocForge visual QA — ${LABEL}</title>
<style>
 body{font:14px/1.5 system-ui,sans-serif;background:#0f1115;color:#e6e9f0;margin:0;padding:24px}
 h1{font-size:20px;margin:0 0 4px} h2{font-size:16px;margin:32px 0 10px;color:#8ab4ff}
 .meta{color:#98a2b3;font-size:13px;margin-bottom:18px}
 table.sum{border-collapse:collapse;margin-bottom:20px;font-size:13px}
 table.sum td,table.sum th{border:1px solid #2a2f3a;padding:5px 10px;text-align:left}
 .row{display:flex;gap:14px;overflow-x:auto;padding-bottom:10px;align-items:flex-start}
 .pg{flex:0 0 auto;background:#fff;border-radius:3px}
 .pg img{display:block;height:460px;width:auto}
 .lbl{color:#98a2b3;font-size:11px;text-align:center;padding:3px 0}
 .side{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:8px}
 .side>div{min-width:0}
 .side h3{font-size:12px;color:#98a2b3;margin:0 0 6px;text-transform:uppercase;letter-spacing:.08em}
 .err{color:#ff8a8a}
</style>
<h1>DocForge visual QA — ${LABEL}</h1>
<div class="meta">torture document · ${new Date().toISOString()} · left column = PDF (Paged.js), right column = Word (rendered via Word → PDF)</div>
<table class="sum"><tr><th>case</th><th>preview</th><th>pdf</th><th>word</th><th>selectable chars</th><th>console</th></tr>
${report.map(r => `<tr><td>${r.id}</td><td>${r.previewPages}</td><td>${r.pdfPages}</td><td>${r.docxPages ?? "—"}</td><td>${r.selectableChars}</td><td class="${r.errors.length ? "err" : ""}">${r.errors.length || "clean"}</td></tr>`).join("")}
</table>
${report.map(r => `
<h2>${r.id}</h2>
<div class="side">
  <div><h3>PDF</h3><div class="row">${r.pdfImgs.map((s, i) => `<div><div class="pg"><img src="${s}" loading="lazy"></div><div class="lbl">${i + 1}</div></div>`).join("")}</div></div>
  <div><h3>Word</h3><div class="row">${r.docxImgs.length ? r.docxImgs.map((s, i) => `<div><div class="pg"><img src="${s}" loading="lazy"></div><div class="lbl">${i + 1}</div></div>`).join("") : "<i style='color:#98a2b3'>not captured</i>"}</div></div>
</div>`).join("")}
`;
writeFileSync(join(OUT, "index.html"), html);
writeFileSync(join(OUT, "report.json"), JSON.stringify(report, null, 2));

console.log(`\ncontact sheet: ${join(OUT, "index.html")}`);
const bad = report.filter(r => r.errors.length);
if (bad.length) { console.log("CONSOLE ERRORS PRESENT"); process.exitCode = 1; }
